# Generated by Django 3.1.4 on 2021-01-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='ArachnidaBitScore',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='ArachnidaCoverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='ArachnidaDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='ArachnidaIdentity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='ArachnidaTopHit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='BestHit',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='SprotBitScore',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='SprotCoverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='SprotDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='SprotIdentity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='SprotTopHit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='TSFBitScore',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='TSFCoverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='TSFDescription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='TSFIdentity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='TSFTopHit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Uniref90BitScore',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Uniref90Coverage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Uniref90Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Uniref90Identity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='Uniref90TopHit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
