# Generated by Django 3.1.4 on 2021-03-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcripts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcript',
            name='MG_FC',
            field=models.DecimalField(decimal_places=3, max_digits=100000000000000, null=True),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='SG_FC',
            field=models.DecimalField(decimal_places=3, max_digits=100000000000000, null=True),
        ),
    ]
